from Tkinter import *
from tkMessageBox import *

root=Tk()
root.title('Billing System')
Label(root,text='Select your Breakfast',font='arial 15 bold').grid(row=0,column=0)
Label(root,text='( Breakfast calculator )',font='arial 14 italic').grid(row=1,column=1)
v1=IntVar()
v2=IntVar()
v3=IntVar()
v4=IntVar()
v5=IntVar()
v6=IntVar()
v7=IntVar()
v8=IntVar()
v9=IntVar()
v10=IntVar()
v11=IntVar()
v12=IntVar()
v13=IntVar()
v14=IntVar()
v15=IntVar()
v16=IntVar()

Checkbutton(root,text='macroni (105)',variable=v1,onvalue=105).grid(row=2,column=0)
Checkbutton(root,text='sandwich (80)',variable=v2,onvalue=80).grid(row=3,column=0)
Checkbutton(root,text='Aloo paratha (200)',variable=v3,onvalue=200).grid(row=4,column=0)
Checkbutton(root,text='poha (50)',variable=v4,onvalue=50).grid(row=5,column=0)
Checkbutton(root,text='noodles (120)',variable=v5,onvalue=120).grid(row=6,column=0)
Checkbutton(root,text='egg (20)',variable=v6,onvalue=20).grid(row=7,column=0)
Checkbutton(root,text='idli (60)',variable=v7,onvalue=60).grid(row=8,column=0)
Checkbutton(root,text='upma (70)',variable=v8,onvalue=70).grid(row=9,column=0)
Checkbutton(root,text='pav bhaji (110)',variable=v9,onvalue=110).grid(row=2,column=1)
Checkbutton(root,text='porage (55)',variable=v10,onvalue=55).grid(row=3,column=1)
Checkbutton(root,text='pasta (80)',variable=v11,onvalue=80).grid(row=4,column=1)
Checkbutton(root,text='omelete (30)',variable=v12,onvalue=30).grid(row=5,column=1)
Checkbutton(root,text='fruits (40)',variable=v13,onvalue=40).grid(row=6,column=1)
Checkbutton(root,text='bread butter (20)',variable=v14,onvalue=20).grid(row=7,column=1)
Checkbutton(root,text='sprouts (65)',variable=v15,onvalue=65).grid(row=8,column=1)
Checkbutton(root,text='milk corn flakes (25)',variable=v16,onvalue=25).grid(row=9,column=1)
def total():
    count=str(v1.get()+v2.get()+v3.get()+v4.get()+v5.get()+v6.get()+v7.get()+v8.get()+v9.get()+v10.get()+v11.get()+v12.get()+v13.get()+v14.get()+v15.get()+v16.get())
    #Label(root,text='total price of your breakfast is :',onvalue=count).grid(row=12)
    print 'total value of your breakfast is :',count
def close():
    root.destroy()
Button(root,text='Check Rs.',command=total).grid(row=11,column=0)
Button(root,text='EXIT',command=close).grid(row=11,column=1)

root.mainloop()
