from Tkinter import *
root=Tk()
v1=IntVar()
v2=IntVar()
v3=IntVar()
v4=IntVar()
root.title('my detail')
Label(root,text='YOUR PERSONAL DETAIL').pack()
Label(root,text='Enter your name : ').pack()
e=Entry()
e.pack()
Label(root,text='Enter your DoB in dd/mm/yyyy :').pack()
d=Entry()
d.pack()
Label(root,text='Please select your heighest Qualification : ').pack()
Checkbutton(root,text='B.Tech',variable=v1,onvalue=10).pack()
Checkbutton(root,text='M.Tech',variable=v2,onvalue=20).pack()
Checkbutton(root,text='PhD.',variable=v3,onvalue=30).pack()
Label(root,text='please select your branch : ').pack()
Radiobutton(root,text='CSE',variable=v4,value=1).pack()
Radiobutton(root,text='ECE',variable=v4,value=2).pack()
Radiobutton(root,text='ME',variable=v4,value=3).pack()
Radiobutton(root,text='CE',variable=v4,value=4).pack()
Radiobutton(root,text='CHE',variable=v4,value=5).pack()
def fun():
    Label(root,text='you are '+e.get()).pack()
Button(root,text='Set Details',command=fun).pack()
root.mainloop()
